name: podbus_workspace
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - packages/podbus_core
  - packages/podbus_nats
  - packages/podbus_rabbitmq
  - packages/podbus_kafka
  - packages/podbus_postgres
  - packages/podbus_observability
  - packages/podbus_serverpod
  - examples/podbus_example
  - examples/podbus_example_client
  - examples/plain_dart_service

dev_dependencies:
  lints: ^6.0.0
  podbus_core:
    path: packages/podbus_core
  podbus_kafka:
    path: packages/podbus_kafka
  podbus_nats:
    path: packages/podbus_nats
  podbus_observability:
    path: packages/podbus_observability
  podbus_postgres:
    path: packages/podbus_postgres
  podbus_rabbitmq:
    path: packages/podbus_rabbitmq
  test: ^1.26.0
